### ISSUE TITLE
Načítání konfiguračního souboru .ini 

### ISSUE THREAD

**Issue by lukaskarabec** [caithaml/AVAS#7]
Načítání konfiguračního souboru .ini pro testování GP atd

**Comment by caithaml** [comment]
Ja pouzivam nasledujici funkci:

$scriptpath = $MyInvocation.MyCommand.Path | Split-Path
####################################################################################
##Nacteni konfigurace ze souboru z create-dp.ini
####################################################################################	
if (!(Test-Path -Path "$scriptpath\create-dp.ini")) 
{
  Write-Host -Object "$(Get-Date) - Nelze najit soubor $scriptpath\create-dp.ini `r"
  Stop-Transcript
  exit
}

Get-Content -Path "$scriptpath\create-dp.ini" | ForEach-Object -Begin {
  $set = @{}
} -Process {
  $k = [regex]::split($_,'=')
  if(($k[0].CompareTo('') -ne 0) -and ($k[0].StartsWith('#') -ne $true)) 
  {
    $set.Add($k[0], $k[1])
  }
}
if($set.debug -eq '1') 
{
  $DebugPreference = 'Continue'
}
else 
{
  $DebugPreference = 'SilentlyContinue'
}

**Comment by lukaskarabec** [comment]
načítání ini souboru doplněno - zatím ještě neuzavírat

**Comment by caithaml** [comment]
zvazit zda nepouzit json format i pro konfiguraci

**Comment by lukaskarabec** [comment]
došlo ke změně na json formát, toto issue uzavírám
