### ISSUE TITLE
Logovani AVASU

### ISSUE THREAD

**Issue by caithaml** [caithaml/AVAS#8]
Kazda jednotliva stanice do samostatneho transcript logu pomoci:
Start-Transcript -Path $jmenostanice_%datum%.log

jednotlive udalosti zapisovat do konzole pomoci napr:
Write-Host -Object "$(Get-Date) - Zastavuji transcript a cekam 10 vterin `r"

**Comment by lukaskarabec** [comment]
logování doplněno
