### ISSUE TITLE
Vytvorit testovaci kontrolu aplikaci

### ISSUE THREAD

**Issue by caithaml** [caithaml/AVAS#9]
Vytvorit kontrolu instalovanych aplikaci
- Kontrola si nacte informace z clixml, ktere bylo vytvoreno pomoci ICWSC
- Kontrola si nacte konfiguraci AVASU z pripraveneho ini souboru
- V ini souboru pro AVAS budou specifikovany aplikace, ktere jsou povoleny vcetne verze
- Kontrola porovna data z nacteneho clixml oproti ini souboru a vyhodi neshody vcetne verze aplikace!

**Comment by lukaskarabec** [comment]
Bude zaimplementováno a nasazeno na github k release testu

**Comment by lukaskarabec** [comment]
- [ X ]     Kontrola si nacte informace z clixml, ktere bylo vytvoreno pomoci ICWSC

    

- [ ] Kontrola si nacte konfiguraci AVASU z pripraveneho ini souboru

 

- [ ]    V ini souboru pro AVAS budou specifikovany aplikace, ktere jsou povoleny vcetne verze

- [ ]     Kontrola porovna data z nacteneho clixml oproti ini souboru a vyhodi neshody vcetne verze aplikace!

**Comment by lukaskarabec** [comment]
Provedena změna - používá se json formát místo ini

**Comment by lukaskarabec** [comment]
Současné použití pomocí compare-object 
`$rozdil=Compare-Object -ReferenceObject (Get-Content C:\Users\lukas\OneDrive\Documents\GitHub\AVAS\app_porovnani\test\app_default.json) -DifferenceObject (Get-Content C:\Users\lukas\OneDrive\Documents\GitHub\AVAS\app_porovnani\test\app.json)`

**Comment by lukaskarabec** [comment]
ponechat stále otevřené, ještě bude pracováno

**Comment by lukaskarabec** [comment]
řešeno také v issue #13

**Comment by lukaskarabec** [comment]
reseno
